name: Bun CI

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  test_pull_request:
    name: test_pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1.1.1

      - run: bun install
      - run: bun run lint
      - run: bun run prettier
      - run: bun run build
